title: Roughly Cairns
email: rebecca.burwei@gmail.com
description: A cairn is a pile of rocks assembled to mark an event, boundary, grave or path ahead.
permalink:     '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
include: ['_pages']
relative_permalinks: false
google_site_verification: U5L5H1-KWT4JlqKnRvrBxv_spUS6bhPr4UKUOALiIgY
google_gtag_id: UA-149276100-1 

# Variables for jekyll-seo-tag plugin
twitter:
  card: summary
  username: Roughy Cairns is not on Twitter.
logo: /assets/img/portfolio.png

# Variables from plainwhite
show_excerpts: true
sass:
  sass_dir: _sass
plainwhite:
  name: "Roughly Cairns"
  date_format: "%Y-%m-%d"
  sitemap: true

# Custom Variables
quotes:
  - "I feel like an old millenial."
  - "I'm a 2nd-gen tech worker."
  - "I'm extremely literal in real life."
  - "My inner hobbit is Gollum."
  - "I'm Chinese and Taiwanese."
  - "I love Fiona Apple's Heavy Balloon."
