title: Rebecca BurWei's Curated Self
author: Rebecca BurWei
email: rebecca.burwei@gmail.com
description: Rebecca BurWei tells insightful stories about machine learning and shared technology.
permalink:     '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
include: ['_pages']
relative_permalinks: false

# Variables for jekyll-feed plugin
feed:
  path: feed.atom

# Variables for jekyll-seo-tag plugin
social:
  name: Rebecca BurWei
  links:
    - https://github.com/r-wei
    - https://www.linkedin.com/in/rebecca-burwei
twitter:
  card: summary
  username: Rebecca BurWei is not on Twitter.
logo: /assets/img/portfolio.png

# Variables from plainwhite
show_excerpts: true
sass:
  sass_dir: _sass
plainwhite:
  name: Rebecca BurWei
  tagline: "Let's build collectivist tech."
  date_format: "%-d %b %Y"
  sitemap: true
  social_links:
    github:  r-wei
    linkedIn: in/rebecca-burwei

# Custom Variables
quotes:
  - "Check out Tech Workers Coalition."
  - "I grew up in academia."
  - "I feel like an old millenial."
  - "I like understandable poetry."
  - "I quantify uncertainty."
  - "I'm a 2nd-gen tech worker."
  - "I'm extremely literal in real life."
  - "Let's build collectivist tech."
  - "My inner hobbit is Gollum."
  - "My love language is math."
  - "Welcome to my curated self."
  - "Yet another randomly chosen string."